[profile.default]
src = "src"
out = "out"
libs = ["lib"]
verbosity = 3
solc = '0.8.22'
optimizer = true
optimizer_runs = 20_000

# See more config options https://github.com/foundry-rs/foundry/blob/master/crates/config/README.md#all-options

# https://book.getfoundry.sh/reference/config/formatter
[fmt]
bracket_spacing = true
line_length = 160
ignore = ['lib']